# DS tracing

Although DS assembly hacking has been done for some time it is not as advanced in terms of power of tools doing it as the GBA and earlier consoles. Equally the cart not being mapped to memory at best complicates the basic resource location methods and places them outside the fairly simple mechanical process that the likes of the GBA enjoys.

## DS debugging emulators

With the possible exception of no$gba DS debugging emulators are not as advanced as the likes of VBA-SDL-h and boycott advance on the GBA.

To this end there are three main emulators with any real debugging support. It is unknown if no$gba debug version can still be legitimately obtained.

no$gba

will not work on later ROMs unless you otherwise bypass any included anti piracy but has a lot of abilities including the ability to set a variety of breakpoints.

desmume

although it features disassembly support and a variety of memory viewing, dumping and editing options (in general and as part of cheats) as well as a full complement of tile, map and other viewers much of the debugging functionality is aimed at homebrew via the GDB stub.

iDeaS

the main claim to debugging status alongside the other two is the support for run to selection and then the step function after that as well as the ability to manipulate registers.

## Cart read command

[GBAtek](http://problemkaputt.de/gbatek.htm#dscartridgeprotocol) details much of the cart read protocol but for most purposes “B7aaaaaaaa000000” where the “a” values are a 32 bit location (in big endian/most significant first no less) is the only command that matters. Do remember the binary is loaded into memory and can contain anything the game might use in addition to the binary itself.

### Basic lookup and methods for it

The command itself more or less sets a window into the ROM image which can be read accordingly

Compression aside With the DS cart not being memory mapped there will occasionally be a copy to ram of data as seen on the cart and a subsequent copy to where it needs to end up (in the case of audio or graphics) can happen not to mention compression will often operate like this.

### Header reverse engineering/generated values

The DS has a filesystem and those files will often house further files or data sections which are unaffected by the filesystem as a whole. This is very nice as it means a whole ROM does not have to be recompiled by the original coders when a small change is made and likewise affords a considerable amount of flexibility as far as ROM hacking is concerned.

It is then quite possible to build up a mathematical expression to find the final location of a file and although many