# Reverse engineering various ROM images

The follow section will be comprised of a basic and in some cases more advanced teardown of a selection of ROMs both random and handpicked to demonstrate certain traits. Although the distinction between genres is not brilliant from an artistic standpoint it is somewhat useful from a technical standpoint. This being said some of the best titles on any system or indeed examples of said genre might well feature elements of other “genres” with one of the most popular options here known as adding RPG elements where what were traditionally stateless (ignoring the odd one use powerup carry over and lives) games level to level gained a small measure of character progression (experience and upgrades being the main methods) becoming a commonly seen term used in discussion of games.

All that and what follows being said play the game, look at some game footage and if you can simply play around with layers in an emulator as that will give you clues as to how things will be set up in the game.

## Large archive on top of filesystem

Although the DS has a filesystem there have been many games that use archives big and small and some that archive their entire game data (maybe give or take some audio or download play).

### 9.1.1 Tony Hawk

One of the earliest examples of this arrived back when people were ripping audio and such from games to get them to fit on smaller devices and as this title had a file larger than most of those carts it.

### 9.1.2 Star Wars - The Force Unleashed

### 9.1.3 El Tigre Make my mule

Used as an example several times already.

## Compression

Compression has been known about and fairly well documented for a long time (the 77 in LZ77 refers to the year it was made) but to do it usefully in real time did not really take off until the GBA and to a slightly lesser extent the 16 bit era. Field specific compression (dual and multi tile encoding, palette swapping and all the other methods covered in developer tricks) and simpler methods like run length encoding have however been around for a long time. The GBA and DS both feature decompression algorithms for two popular methods (LZSS and Huffman) of various flavours inbuilt into the BIOS and well supported in official developer kits. The BIOS decompression was not always used as they were a tradeoff between usefulness, resources required, size in the BIOS and overall speed which led to developers either implementing faster methods to decompress files compressed with otherwise standard BIOS compression or implementing a custom method of compression.

Typically custom usually just means it allows for different lengths or compression or uses a custom flag type (the BIOS compression is quite strict as to what it requires in a compressed format) rather than a truly new idea as to how to compress things for as with most areas of science and technology massive leaps are quite rare but small refinements are quite possible. To this end if you know how compression works and can think through what you would change to improve compression you will usually be OK.

Likewise where developers do want to reduce sizes (ROM chip sizes increase in powers of 2 and price does as well and one hundred thousand times the difference in price adds up to quite a bit) but ROM hackers are not always so limited (memory issues aside) so removing the compression in the first place can be done and often is. In some cases removing compression actually speeds up the game as well.

Remember on the GBA you will usually have the whole upper 16 megabytes to play with and the DS is limited to 512 megabytes for the ROM which again few ROMs ever get/got up to not to mention being able to create two ROMs and say play to this point then swap.

GBA

## First Person Game

There are two main classes of games viewed from the first person.

1.  Those that attempt to use the DS 3d to make a game
2.  Those that use more conventional 2d animations

Naturally there are combinations of the two as seen in the platform type games which use 3d. The DS 3d is not terribly powerful though so some games opted to make more traditional style shooting gallery type games which were layers and sprites. Prerendered 3d backgrounds did feature and similar techniques seen in early dungeon crawling titles where the camera was moved from fixed point to fixed point or isometric imagery was possible but that is leaving first person.

A few GBA games (mainly ports of older Doom 1 era first person shooters and film tie in games doing similar things) did however use bitmap modes to try to do actual 3d and as a mode7 style perspective transformation was possible on the GBA (and DS) mode7 style methods could happen..

## Platformer

For most here the big distinction is between 2d and 3d but that might not be a great one as far as looking at what sorts of files will make up a game (both types will usually have levels themselves (even if they are 3d it will still have some mapping data for the objects and items), the objects and items and any animations they do.

## Fighting games

For most they are usually broken into fixed stage (street fighter, tekken, powerstone) and scrolling stage (Streets of Rage, Golden Axe, earlier Castlevania games) but that is not that useful as many times the scrolling stage will be an illusion as you might walk on and then get a signal to continue after defeating so many enemies. The distinction between 2d and various forms of 3d are also possible.

## Role playing games

A variety of methods have been seen here and categorisation is extremely hard. For the most part though the ideas of world map, town/castle maps (or indeed shops), full worlds (either classic dungeon crawler or “full” 3d) and where any “battles” will be located (separate locations on in level). There are an enormous number of tweaks to various formulas (random battles vs enemies on the world map, turn based vs active battling) that can have a radical effect on the main game but beyond a routine handling things on a world map or dungeon map they might have little effect on the files and their contents.

## Racing games

There are several techniques used to make racing games although in practice it boils down to four methods as far as technology goes

1.  Overhead 2d and isometric 3d (micro machines and Racing Gears Advance)
2.  Conventional 2d (Space harrier, Outrun and Road Rash)
3.  Mode7 style (SNES FZero, Mario Kart SNES and GBA)
4.  Full 3d (Most DS racing games)

Overhead 2d and isometric usually use similar methods

Conventional 2d are usually left and right “race to the horizon” affairs with turning usually being something of an illusion and any vertical movement even more so.

Mode 7 is technically 2d but is different enough in concept as it allowed proper turning.

Full 3d is as full 3d usually is (although 2d skyboxes are possible) and a full 3d world is made.

## Puzzle

One of the commonly seen things in puzzle games is much of the text is rendered as an actual graphic and stored in a similar manner to graphics usually as there is not enough text to warrant a full engine. This not to say there can not be text in the game but as rendering a fancy font would take serious effort much of the text may still be as graphics. They are also some of the most likely to be incorporated into other “genres” (Puzzle Quest being a good example although it goes further and there have been a few mahjong (not solitaire) titles wrapped in what many would

Broadly speaking they are subdivided into two classed

1.  Computerised versions of traditional card/board/item games
2.  Reflex testing games

Computerised versions of traditional games (or indeed not so traditional games but ones that could have been) vary as widely as the games themselves. Indeed how to have a computer play them is often a field in computing unto itself or at least a recognised problem (Chess and Go being two of the most famous although games like [mahjong](http://cs229.stanford.edu/proj2009/Loh.pdf) are well studied too). In many cases this also leads to the AI in said games being classified as broken or broken by modifications most humans are quite happy to handle and might not even notice unless they take the time to truly analyse it.

Reflex testing games on the other hand tend to have more in common with other types of games (the Kururin series for instance is often classified as a puzzle game but seeing it run would see most hackers approach it as they would a platform game). Although there have been a few attempts at capturing real world reflex testing games few have worked that well and many are truly quite abstract (consider what Tetris truly is for a moment).

### 9.8.1 Mahjong game

### 9.8.2 Tetris

## Other genres

Probably the most notable other genres are those of the visual novel, simulation and point and click adventure although in recent years the visual novel and point and click adventure have become somewhat intertwined (see games like Ace Attorney/Phoenix Wright). Equally many games that might have at one time been aimed at a visual novel format have instead opted to use a 3d engine instead although that heads more towards the art games territory. It should be noted visual novels have many examples of ultra simple titles consisting of nothing but a few images (with text in the images) to full on scripting languages so assuming it will always be simple is not a good idea.

Other common genres include music games, artistic games (painting and such) and utility games (language learning being a common example) but other than music games almost invariably use extra formats to work most of those will usually want to be approached on a game by game basis.