# 14 Game design and media

There is a long history of those engaged in science and engineering and those engaged in more artistic pursuits not seeing eye to eye (indeed there is a very good chance that after you as a ROM hacker have figured out a format and maybe made a proof of concept that you will hand it over to an artist to make it look nice) but it is well worth knowing the basics of the “other side” as it will help figure out why something was done, allow you to envisage how you might improve something and might even allow you to do something you otherwise deemed impossible (indeed as mentioned elsewhere the whole of game AI is based around trying to use a combination of simplistic routines to provide some challenge to a human being that for the time being at least is far smarter than the machine they are playing with and very different in terms of operating logic) or at least work more efficiently within limits.

Now such fields are somewhat outside the scope of this document but if you are reading this chances are you have the internet and as such it is worth noting that very high level discussion of topics including games, video/film making, literary works (both fiction and argumentative techniques) and the conventions and expectations of each medium are readily available as well as more subjects like psychology and game theory.

Related to this is the concept that game developers and localisation teams are usually under a lot of pressure to put the game out by a certain date with certain restrictions and as such might cut corners which you might be able to exploit or have to work around.