# Sound

## SDAT

SDAT is the dominant audio format on the DS and although by itself it contains no sound information it holds the locations and relationships between the various files it contains.

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |

## SSEQ

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |

## STRM

Occasionally seen outside the SDAT file. “Officially” the only one that does.

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |

## SWAR

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |

## SWAR

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |

## BANK

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |

## Other formats

See http://gbatemp.net/topic/305167-the-various-audio-formats-of-the-ds/

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |

|     |     |     |
| --- | --- | --- |
| &emsp; | &emsp; | &emsp; |
| Location | Size | Description |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |
| &emsp; | &emsp; | &emsp; |